//! Pipeline stages for document processing
//!
//! Each stage handles a specific part of the document processing pipeline.

pub mod analysis;
pub mod chunking;
pub mod embedding;
pub mod indexing;
pub mod ingestion;
pub mod metadata;
pub mod parsing;
pub mod storage;

pub use analysis::AIAnalysisStage;
pub use chunking::{ChunkingStage, ChunkingStrategy};
pub use embedding::{EmbeddingStage, EmbeddingProvider};
pub use indexing::IndexingStage;
pub use ingestion::{DocumentSource, IngestionInput, IngestionStage, RawDocument};
pub use metadata::MetadataExtractionStage;
pub use parsing::{ParsedDocument, ParsingStage};
pub use storage::{StorageStage, StoredDocument};

/// Final output after all pipeline stages complete
#[derive(Debug, Clone)]
pub struct PipelineOutput {
    /// The stored document ID
    pub document_id: uuid::Uuid,

    /// Document title
    pub title: String,

    /// Number of chunks created
    pub chunks_count: usize,

    /// Whether AI analysis was performed
    pub analyzed: bool,

    /// Topics extracted by AI (if analysis was performed)
    pub topics: Vec<String>,

    /// Summary generated by AI (if analysis was performed)
    pub summary: Option<String>,
}
