services:
  app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://minky_user:minky_password@db:5432/minky_db
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-jwt-secret-key}
      - FLASK_ENV=production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./migrations:/app/migrations
      - ./backup:/app/backup
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:3.1.0
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m" # Adjust memory as needed
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=StrongP@ssw0rd!
    ports:
      - "9200:9200"
      - "9600:9600" # for performance analyzer
    volumes:
      - ./opensearch_data:/usr/share/opensearch/data
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=minky_db
      - POSTGRES_USER=minky_user
      - POSTGRES_PASSWORD=minky_password
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minky_user -d minky_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - app
    restart: unless-stopped

