"""Add performance indexes for documents and tags

Revision ID: e82c3fec2746
Revises: b1c2d3e4f5g6
Create Date: 2026-02-12 10:29:49.338764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82c3fec2746'
down_revision = 'b1c2d3e4f5g6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('idx_documents_category_id', ['category_id'], unique=False)
        batch_op.create_index('idx_documents_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_documents_is_public', ['is_public'], unique=False)
        batch_op.create_index('idx_documents_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('idx_documents_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_documents_user_visibility', ['user_id', 'is_public'], unique=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('idx_tags_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_tags_created_by', ['created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('idx_tags_created_by')
        batch_op.drop_index('idx_tags_created_at')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('idx_documents_user_visibility')
        batch_op.drop_index('idx_documents_user_id')
        batch_op.drop_index('idx_documents_updated_at')
        batch_op.drop_index('idx_documents_is_public')
        batch_op.drop_index('idx_documents_created_at')
        batch_op.drop_index('idx_documents_category_id')

    # ### end Alembic commands ###
