-- Add local embedding model variant
-- Allows the `embedding_model` enum to store rows generated by the
-- fastembed-rs nomic-embed-text-v1.5 (768-dim) local model.
DO $$ BEGIN
    ALTER TYPE embedding_model ADD VALUE IF NOT EXISTS 'nomic_embed_text_v1_5';
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;
